# Generated by Django 2.2.5 on 2022-05-01 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='relationship',
            field=models.ManyToManyField(related_name='_customuser_relationship_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
