# Generated by Django 2.2.5 on 2022-05-01 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220501_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='relationship',
        ),
        migrations.AddField(
            model_name='customuser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_customuser_followers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='_customuser_followings_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
